"""Generate FastAPI routes from JourneySpec steps."""

from ..parser.ast_nodes import (
    Action,
    Entity,
    JourneySpec,
    Step,
)
from ..core.normalize import slugify


def _snake(name: str) -> str:
    result = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0:
            result.append("_")
        result.append(ch.lower())
    return "".join(result)


def _plural(name: str) -> str:
    if name.endswith("s"):
        return name + "es"
    if name.endswith("y"):
        return name[:-1] + "ies"
    return name + "s"


def _step_class_name(step_name: str) -> str:
    return "".join(word.title() for word in step_name.split("_"))


def _route_path(step: Step) -> str:
    """Map step name to URL path."""
    name = step.name.replace("_", "-")
    # Heuristics for RESTful paths
    if "signup" in step.name:
        return "/signup"
    if "login" in step.name:
        return "/login"
    if step.name == "verify_email":
        return "/verify-email"
    if "create_workspace" in step.name:
        return "/workspaces"
    if "invite_member" in step.name:
        return "/invitations"
    if "accept_invite" in step.name:
        return "/invitations/accept"
    return f"/{name}"


def _http_method(step: Step) -> str:
    """Infer HTTP method from step actions."""
    for action in step.actions:
        if action.kind == "create":
            return "post"
    return "post"  # Default to POST for journey steps


def _status_code(step: Step) -> int:
    """Infer default success status code."""
    for action in step.actions:
        if action.kind == "create":
            return 201
    return 200


def generate_routes(spec: JourneySpec) -> str:
    """Generate the complete routes.py file."""
    # Collect all model imports needed
    model_imports = set()
    schema_imports = set()

    for entity in spec.entities:
        model_imports.add(entity.name)
        for field in entity.fields:
            if field.state_type:
                model_imports.add(f"{entity.name}Status")
            if field.enum_type:
                model_imports.add(f"{entity.name}{field.name.title().replace('_', '')}")

    # Check for WorkspaceMember
    for step in spec.steps:
        for action in step.actions:
            if action.kind == "call" and action.target == "add_member":
                model_imports.add("WorkspaceMember")

    for step in spec.steps:
        schema_imports.add(f"{_step_class_name(step.name)}Request")
        schema_imports.add(f"{_step_class_name(step.name)}Response")
    schema_imports.add("ErrorResponse")

    slug = slugify(spec.name)
    tag = spec.name

    lines = [
        '"""',
        "AUTO-GENERATED by Journey compiler",
        "DO NOT EDIT — regenerate with: journey compile <source>.journey",
        '"""',
        "",
        "from datetime import datetime, timedelta, timezone",
        "import os",
        "from uuid import uuid4",
        "",
        "import bcrypt as _bcrypt",
        "",
        "from fastapi import APIRouter, Depends, HTTPException",
        "from sqlalchemy.orm import Session",
        "",
        "",
        "def _hash_password(password: str) -> str:",
        "    return _bcrypt.hashpw(password.encode(), _bcrypt.gensalt()).decode()",
        "",
        "",
        "def _verify_password(password: str, hashed: str) -> bool:",
        "    return _bcrypt.checkpw(password.encode(), hashed.encode())",
        "",
        "from .database import get_db",
        f"from .models import (",
        f"    {','.join(f'{chr(10)}    ' + m if i > 0 else m for i, m in enumerate(sorted(model_imports)))}",
        ")",
        f"from .schemas import (",
        f"    {','.join(f'{chr(10)}    ' + s if i > 0 else s for i, s in enumerate(sorted(schema_imports)))}",
        ")",
        "",
        f'router = APIRouter(prefix="/journey/{slug}", tags=["{tag}"])',
        "",
        "# --- In-memory sessions (pluggable via journey config) ---",
        "",
        "SESSION_TTL_HOURS = int(os.getenv(\"JOURNEY_SESSION_TTL_HOURS\", \"24\"))",
        "_sessions: dict[str, dict] = {}",
        "",
        "",
        "async def get_current_user(token: str, db: Session = Depends(get_db)):",
        '    session = _sessions.get(token)',
        '    if not session:',
        '        raise HTTPException(status_code=401, detail="Invalid or expired token")',
        '    if session["expires_at"] <= datetime.now(timezone.utc):',
        "        _sessions.pop(token, None)",
        '        raise HTTPException(status_code=401, detail="Invalid or expired token")',
        '    from .models import User',
        '    user = db.query(User).filter(User.id == session["user_id"]).first()',
        '    if not user:',
        '        raise HTTPException(status_code=401, detail="User not found")',
        '    return user',
        "",
    ]

    # Generate each step as a route
    for step in spec.steps:
        lines.append("")
        lines.extend(_gen_route(step, spec))

    return "\n".join(lines) + "\n"


def _gen_route(step: Step, spec: JourneySpec) -> list[str]:
    """Generate a single route handler."""
    class_name = _step_class_name(step.name)
    path = _route_path(step)
    method = _http_method(step)
    status = _status_code(step)

    # Function signature
    params = [f"body: {class_name}Request", "db: Session = Depends(get_db)"]
    if step.actor.authenticated:
        params.append("current_user = Depends(get_current_user)")

    decorator_kwargs = f'"{path}", response_model={class_name}Response'
    if status != 200:
        decorator_kwargs += f", status_code={status}"

    lines = [
        f"@router.{method}({decorator_kwargs})",
        f"async def {step.name}({', '.join(params)}):",
    ]

    # Generate error checks first
    for error in step.errors:
        lines.extend(_gen_error_check(error, step, spec))

    # Generate action code
    variables = {}  # Track variable assignments for action code gen
    for action in step.actions:
        action_lines = _gen_action(action, step, spec, variables)
        lines.extend(action_lines)

    # Generate return
    return_fields = []
    for out in step.outputs:
        expr = out.expression
        if "." not in expr:
            # Literal string
            return_fields.append(f'{out.name}="{expr}"')
        else:
            # Dotted expression — map to Python
            return_fields.append(f"{out.name}={_map_expression(expr, variables)}")

    lines.append(f"    return {class_name}Response({', '.join(return_fields)})")

    return lines


def _gen_error_check(error, step, spec) -> list[str]:
    """Generate error check code based on error semantics."""
    lines = []

    if error.code_name == "email_taken":
        # Check for duplicate email
        lines.extend([
            "    existing = db.query(User).filter(User.email == body.email).first()",
            "    if existing:",
            f'        raise HTTPException(status_code={error.http_status}, detail="{error.message}")',
        ])
    elif error.code_name == "invalid_token":
        pass  # Handled in find action
    elif error.code_name == "invalid_credentials":
        pass  # Handled in login logic
    elif error.code_name == "account_pending":
        pass  # Handled in login logic
    elif error.code_name == "not_owner":
        pass  # Handled in find action
    elif error.code_name == "already_invited":
        pass  # Generated after workspace lookup
    elif error.code_name == "invalid_invite":
        pass  # Handled in find action
    elif error.code_name == "already_member":
        pass  # Generated after invitation lookup
    elif error.code_name == "limit_reached":
        pass  # Application-specific limit check
    # Other errors are checked inline during action generation

    return lines


def _gen_action(action: Action, step: Step, spec: JourneySpec, variables: dict) -> list[str]:
    """Generate code for a single action."""
    lines = []

    if action.kind == "create":
        lines.extend(_gen_create_action(action, step, spec, variables))
    elif action.kind == "find":
        lines.extend(_gen_find_action(action, step, spec, variables))
    elif action.kind == "transition":
        lines.extend(_gen_transition_action(action, step, spec, variables))
    elif action.kind == "send":
        lines.append(f"    # Action: {action.raw} — stubbed, emits event for provider")
    elif action.kind == "verify":
        lines.extend(_gen_verify_action(action, step, spec, variables))
    elif action.kind == "call":
        lines.extend(_gen_call_action(action, step, spec, variables))

    return lines


def _gen_create_action(action: Action, step: Step, spec: JourneySpec, variables: dict) -> list[str]:
    lines = []
    entity_name = action.target
    var = action.variable or _snake(entity_name)
    variables[var] = entity_name

    # Build constructor kwargs
    kwargs = []
    entity = spec.get_entity(entity_name)
    for key, val in action.params.items():
        if key.startswith("data."):
            continue  # Nested data for send actions, skip
        py_val = _map_param_value(val, step, variables)
        field = next((f for f in entity.fields if f.name == key), None) if entity else None
        # Map field names that might differ in model
        if key == "password":
            kwargs.append(f"password_hash=_hash_password({py_val})")
        elif field and field.ref_entity:
            kwargs.append(f"{key}_id={py_val}.id")
        elif key == "owner":
            kwargs.append(f"owner_id={py_val}.id")
        elif key == "workspace":
            kwargs.append(f"workspace_id={py_val}.id" if py_val != "workspace" else f"workspace_id={py_val}.id")
        elif key == "status":
            # Find the status enum
            for entity in spec.entities:
                if entity.name == entity_name:
                    for f in entity.fields:
                        if f.name == "status" and f.state_type:
                            enum_cls = f"{entity_name}Status"
                            kwargs.append(f"status={enum_cls}.{val}")
                            break
                    break
            else:
                kwargs.append(f"status={py_val}")
        elif field and field.enum_type and not val.startswith("input."):
            enum_cls = f"{entity_name}{field.name.title().replace('_', '')}"
            kwargs.append(f"{key}={enum_cls}.{val}")
        else:
            kwargs.append(f"{key}={py_val}")

    constructor = f"{entity_name}({', '.join(kwargs)})"
    lines.extend([
        f"    {var} = {constructor}",
        f"    db.add({var})",
        f"    db.commit()",
        f"    db.refresh({var})",
    ])

    return lines


def _gen_find_action(action: Action, step: Step, spec: JourneySpec, variables: dict) -> list[str]:
    lines = []
    entity_name = action.target
    var = action.variable or _snake(entity_name)
    variables[var] = entity_name

    # Build filter conditions
    filters = []
    for key, val in action.params.items():
        py_val = _map_param_value(val, step, variables)
        if key == "owner":
            filters.append(f"{entity_name}.owner_id == {py_val}.id")
        elif key == "status":
            # Map to enum
            for entity in spec.entities:
                if entity.name == entity_name:
                    for f in entity.fields:
                        if f.name == "status" and f.state_type:
                            enum_cls = f"{entity_name}Status"
                            filters.append(f"{entity_name}.status == {enum_cls}.{val}")
                            break
                    break
            else:
                filters.append(f"{entity_name}.status == {py_val}")
        else:
            filters.append(f"{entity_name}.{key} == {py_val}")

    filter_str = ", ".join(filters)

    lines.extend([
        f"    {var} = db.query({entity_name}).filter({filter_str}).first()",
    ])

    # Find relevant error for this find action
    error_for_find = None
    for err in step.errors:
        if "not_found" in err.code_name or "invalid" in err.code_name or "not_owner" in err.code_name:
            error_for_find = err
            break

    if error_for_find:
        lines.extend([
            f"    if not {var}:",
            f'        raise HTTPException(status_code={error_for_find.http_status}, detail="{error_for_find.message}")',
        ])

    # Check for related error conditions (already_invited, already_member)
    for err in step.errors:
        if err.code_name == "already_invited" and entity_name == "Workspace":
            lines.extend([
                "    existing_invite = db.query(Invitation).filter(",
                f"        Invitation.workspace_id == {var}.id,",
                "        Invitation.email == body.email,",
                "        Invitation.status == InvitationStatus.pending,",
                "    ).first()",
                "    if existing_invite:",
                f'        raise HTTPException(status_code={err.http_status}, detail="{err.message}")',
            ])
        elif err.code_name == "already_member" and entity_name == "Invitation":
            lines.extend([
                "    existing_member = db.query(WorkspaceMember).filter(",
                f"        WorkspaceMember.workspace_id == {var}.workspace_id,",
                "        WorkspaceMember.user_id == current_user.id,",
                "    ).first()",
                "    if existing_member:",
                f'        raise HTTPException(status_code={err.http_status}, detail="{err.message}")',
            ])

    return lines


def _gen_transition_action(action: Action, step: Step, spec: JourneySpec, variables: dict) -> list[str]:
    """Generate state transition code."""
    var = action.target
    new_state = action.params.get("to", "")

    entity_name = variables.get(var, "")
    enum_cls = f"{entity_name}Status"

    lines = [
        f"    {var}.transition_to({enum_cls}.{new_state})",
    ]

    # If transitioning user status to active, consume the verification token
    if entity_name == "User" and new_state == "active":
        lines.append(f"    {var}.verification_token = None")

    lines.append("    db.commit()")
    return lines


def _gen_verify_action(action: Action, step: Step, spec: JourneySpec, variables: dict) -> list[str]:
    """Generate verification code (e.g., password check)."""
    lines = []

    if action.target == "password":
        # Password verification
        params = list(action.params.values())
        input_pass = _map_param_value(params[0], step, variables, spec) if params else "body.password"
        stored_hash = _map_param_value(params[1], step, variables, spec) if len(params) > 1 else "user.password_hash"

        # Find the relevant error
        err = None
        for e in step.errors:
            if "credential" in e.code_name or "password" in e.code_name:
                err = e
                break

        # The find action above already checked if user exists, but we need to
        # handle "user not found" as part of the credential error
        if err:
            lines.extend([
                f"    if not _verify_password({input_pass}, {stored_hash}):",
                f'        raise HTTPException(status_code={err.http_status}, detail="{err.message}")',
            ])

        # Check for account_pending error
        # Derive the variable name from the stored_hash expression
        entity_var = stored_hash.split(".")[0]
        for e in step.errors:
            if "pending" in e.code_name:
                lines.extend([
                    f"    if {entity_var}.status == UserStatus.pending:",
                    f'        raise HTTPException(status_code={e.http_status}, detail="{e.message}")',
                ])

    return lines


def _gen_call_action(action: Action, step: Step, spec: JourneySpec, variables: dict) -> list[str]:
    """Generate code for function calls."""
    lines = []

    if action.target == "create_session":
        var = action.variable or "session"
        user_var = _map_param_value(list(action.params.values())[0], step, variables)
        lines.extend([
            f"    token = uuid4().hex",
            f"    expires = datetime.now(timezone.utc) + timedelta(hours=SESSION_TTL_HOURS)",
            f'    _sessions[token] = {{"user_id": {user_var}.id, "expires_at": expires}}',
        ])
        # Store synthetic variable for output mapping
        variables[var] = "_session"
    elif action.target == "add_member":
        params = list(action.params.values())
        workspace_expr = _map_param_value(params[0], step, variables) if params else "invitation.workspace_id"
        user_expr = _map_param_value(params[1], step, variables) if len(params) > 1 else "current_user"
        role_expr = _map_param_value(params[2], step, variables) if len(params) > 2 else "invitation.role"

        # Resolve workspace_id
        ws_id = workspace_expr
        if not ws_id.endswith("_id") and not ws_id.endswith(".id"):
            ws_id = f"{ws_id}_id" if "." in ws_id else f"{ws_id}.id"

        lines.extend([
            f"    member = WorkspaceMember(",
            f"        workspace_id={ws_id.replace('.workspace', '.workspace_id')},",
            f"        user_id={user_expr}.id,",
            f"        role={role_expr},",
            f"    )",
            f"    db.add(member)",
            f"    db.commit()",
        ])

    return lines


def _map_param_value(val: str, step: Step, variables: dict, spec: "JourneySpec" = None) -> str:
    """Map a parameter value from the journey spec to Python."""
    if val.startswith("input."):
        field_name = val.split(".", 1)[1]
        return f"body.{field_name}"
    if val == "actor":
        return "current_user"
    if val.startswith("actor."):
        return f"current_user.{val.split('.', 1)[1]}"

    # Check if this references a hashed field on an entity variable
    if "." in val and spec:
        parts = val.split(".", 1)
        var_name, field_name = parts
        entity_name = variables.get(var_name, "")
        if entity_name:
            for entity in spec.entities:
                if entity.name == entity_name:
                    for f in entity.fields:
                        if f.name == field_name and f.modifiers.hashed:
                            return f"{var_name}.{field_name}_hash"
                    break

    return val


def _map_expression(expr: str, variables: dict) -> str:
    """Map an output expression to Python."""
    parts = expr.split(".")

    if len(parts) >= 2:
        var = parts[0]
        field = ".".join(parts[1:])

        # Special handling for session variables
        entity_type = variables.get(var, "")
        if entity_type == "_session":
            if field == "token":
                return "token"
            elif field == "expires_at":
                return "expires"

        return f"{var}.{field}"

    return expr
