"""Generate FastAPI app.py entrypoint."""

from ..parser.ast_nodes import JourneySpec


def _snake(name: str) -> str:
    result = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0:
            result.append("_")
        result.append(ch.lower())
    return "".join(result)


def generate_app(spec: JourneySpec) -> str:
    slug = _snake(spec.name).replace(" ", "-").replace("_", "-")
    return f'''"""
AUTO-GENERATED by Journey compiler
DO NOT EDIT — regenerate with: journey compile <source>.journey
"""

from contextlib import asynccontextmanager

from fastapi import FastAPI

from .database import init_db
from .routes import router


@asynccontextmanager
async def lifespan(app: FastAPI):
    init_db()
    yield


app = FastAPI(
    title="{spec.name}",
    description="{spec.description or ""}",
    version="0.1.0",
    lifespan=lifespan,
)

app.include_router(router)
'''
