"""Generate pytest test file from JourneySpec test blocks."""

from ..parser.ast_nodes import JourneySpec, TestBlock, TestCommand
from ..core.normalize import slugify
from .gen_common import route_path


def _step_class_name(name: str) -> str:
    return "".join(word.title() for word in name.split("_"))


def _test_class_name(name: str) -> str:
    """Convert test name to a valid Python class name."""
    words = name.replace("-", " ").replace("_", " ").split()
    return "Test" + "".join(w.title() for w in words)


def generate_tests(spec: JourneySpec) -> str:
    """Generate test_journey.py from spec test blocks."""

    route_prefix = f"/journey/{slugify(spec.name)}"
    needs_verification_token = any(
        cmd.step_name == "verify_email"
        for test_block in spec.tests
        for cmd in test_block.commands
    )
    model_import = "from .models import Base, User" if needs_verification_token else "from .models import Base"

    lines = [
        '"""',
        f"AUTO-GENERATED by Journey compiler",
        "DO NOT EDIT — regenerate with: journey compile <source>.journey",
        "",
        "Run: pytest test_journey.py -v",
        '"""',
        "",
        "import anyio",
        "import httpx",
        "import pytest",
        "from sqlalchemy import create_engine",
        "from sqlalchemy.orm import sessionmaker",
        "from sqlalchemy.pool import StaticPool",
        "",
        "from .app import app",
        "from .database import get_db",
        model_import,
        "",
        '# In-memory SQLite shared across threads (StaticPool keeps one connection alive)',
        'TEST_ENGINE = create_engine(',
        '    "sqlite:///:memory:",',
        '    connect_args={"check_same_thread": False},',
        '    poolclass=StaticPool,',
        ')',
        "TestSession = sessionmaker(bind=TEST_ENGINE)",
        "",
        "",
        "@pytest.fixture(autouse=True)",
        "def fresh_db():",
        '    """Each test gets a clean database."""',
        "    Base.metadata.create_all(bind=TEST_ENGINE)",
        "    yield",
        "    Base.metadata.drop_all(bind=TEST_ENGINE)",
        "",
        "",
        "@pytest.fixture",
        "def db():",
        "    session = TestSession()",
        "    try:",
        "        yield session",
        "    finally:",
        "        session.close()",
        "",
    ]

    if needs_verification_token:
        lines.extend([
            "",
            "def get_verification_token(db, email: str) -> str:",
            '    """Read verification token from DB (simulates reading email)."""',
            "    user = db.query(User).filter(User.email == email).first()",
            '    assert user is not None, f"No user found with email {email}"',
            '    assert user.verification_token is not None, "No verification token"',
            "    return user.verification_token",
            "",
        ])

    for test_block in spec.tests:
        lines.append("")
        lines.extend(_gen_test_class(test_block, route_prefix, spec))

    return "\n".join(lines) + "\n"


def _gen_test_class(block: TestBlock, prefix: str, spec: JourneySpec) -> list[str]:
    class_name = _test_class_name(block.name)
    lines = [
        f"class {class_name}:",
        f'    """journey test \\"{block.name}\\\""""',
        "",
    ]

    method_name = f"test_{block.name.replace(' ', '_').replace('-', '_')}"
    lines.extend([
        f"    def {method_name}(self, db):",
        "        async def run():",
        "            async def _get_test_db():",
        "                try:",
        "                    yield db",
        "                finally:",
        "                    pass",
        "            app.dependency_overrides[get_db] = _get_test_db",
        "            transport = httpx.ASGITransport(app=app)",
        "            try:",
        "                async with httpx.AsyncClient(",
        "                    transport=transport, base_url=\"http://testserver\"",
        "                ) as client:",
    ])

    # Track captured variables
    captured = {}
    session_tokens = set()

    for cmd in block.commands:
        lines.extend(f"            {line}" if line else line for line in _gen_test_command(cmd, prefix, captured, session_tokens, spec))

    lines.extend([
        "            finally:",
        "                app.dependency_overrides.clear()",
        "        anyio.run(run)",
    ])

    return lines


def _gen_test_command(cmd: TestCommand, prefix: str, captured: dict, session_tokens: set[str], spec: JourneySpec) -> list[str]:
    lines = []
    step = spec.get_step(cmd.step_name)
    path = f"{prefix}{route_path(step) if step else '/' + cmd.step_name.replace('_', '-')}"

    # Build the JSON body
    json_parts = []
    for key, val in cmd.args.items():
        if key.isdigit():
            continue  # Skip positional args in test commands
        # Check if the value references a captured variable
        if val in captured:
            json_parts.append(f'"{key}": {val}')
        else:
            json_parts.append(f'"{key}": "{val}"')

    json_body = "{" + ", ".join(json_parts) + "}"

    # Build request params
    auth_token_var = cmd.auth_token_var
    if not auth_token_var and step and step.actor.authenticated and session_tokens:
        auth_token_var = sorted(session_tokens)[-1]

    if auth_token_var:
        lines.append(f"        resp = await client.post(")
        lines.append(f'            "{path}",')
        lines.append(f"            json={json_body},")
        lines.append(f'            params={{"token": {auth_token_var}}},')
        lines.append(f"        )")
    else:
        lines.append(f"        resp = await client.post(")
        lines.append(f'            "{path}",')
        lines.append(f"            json={json_body},")
        lines.append(f"        )")

    # Generate assertions
    for exp in cmd.expectations:
        if exp.kind == "status":
            lines.append(f"        assert resp.status_code == {exp.target}")
        elif exp.kind == "output":
            if exp.value == "exists":
                lines.append(f'        assert "{exp.target}" in resp.json()')
            elif exp.value:
                lines.append(f'        assert resp.json()["{exp.target}"] == "{exp.value}"')
        elif exp.kind == "error":
            # Error expectation — just check the status code was an error
            pass

    # Handle special captures
    if cmd.capture:
        if cmd.step_name == "verify_email":
            # This is handled differently — token comes from DB
            pass
        else:
            lines.append(f'        {cmd.capture} = resp.json()["{cmd.capture}"]')
        captured[cmd.capture] = True
        if step and any(output.name == cmd.capture and output.expression == "session.token" for output in step.outputs):
            session_tokens.add(cmd.capture)

    # Special handling for verify_email step: token comes from email (DB)
    if cmd.step_name == "verify_email" and "last_email.token" in str(cmd.args):
        # The token arg references last_email.token — we need to get it from DB
        # Find the email from a previous signup
        lines_before = [
            f"        token = get_verification_token(db, \"{_find_email_from_context(cmd, captured)}\")",
        ]
        # Replace the json body with the token variable
        for i, line in enumerate(lines):
            if '"token": "last_email.token"' in line:
                lines[i] = line.replace('"token": "last_email.token"', '"token": token')
        lines = lines_before + lines

    lines.append("")
    return lines


def _find_email_from_context(cmd: TestCommand, captured: dict) -> str:
    """Try to find the email used in earlier commands (for token lookup)."""
    # This is a simplification — in a real implementation we'd track this more carefully
    return "alice@example.com"
