"""Generate database.py setup."""

from ..parser.ast_nodes import JourneySpec


def generate_database(spec: JourneySpec) -> str:
    return '''"""
AUTO-GENERATED by Journey compiler
DO NOT EDIT — regenerate with: journey compile <source>.journey
"""

import os

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from .models import Base

DATABASE_URL = os.getenv("JOURNEY_DATABASE_URL", "sqlite:///./journey.db")

connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}
engine = create_engine(DATABASE_URL, connect_args=connect_args)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


def init_db():
    Base.metadata.create_all(bind=engine)


async def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
'''
