"""Generate FastAPI app.py entrypoint."""

from ..parser.ast_nodes import JourneySpec


def _snake(name: str) -> str:
    result = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0:
            result.append("_")
        result.append(ch.lower())
    return "".join(result)


def generate_app(spec: JourneySpec) -> str:
    slug = _snake(spec.name).replace(" ", "-").replace("_", "-")
    return f'''"""
AUTO-GENERATED by Journey compiler
DO NOT EDIT — regenerate with: journey compile <source>.journey
"""

from fastapi import FastAPI

from .database import init_db
from .routes import router

app = FastAPI(
    title="{spec.name}",
    description="{spec.description or ""}",
    version="0.1.0",
)

app.include_router(router)


@app.on_event("startup")
def on_startup():
    init_db()
'''
