"""Generate Pydantic schemas from JourneySpec steps."""

from ..parser.ast_nodes import JourneySpec, Step, InputField, OutputField


def _step_class_name(step_name: str) -> str:
    """signup -> Signup, verify_email -> VerifyEmail."""
    return "".join(word.title() for word in step_name.split("_"))


def _pydantic_type(field: InputField) -> str:
    """Map journey types to Pydantic field types."""
    if field.enum_type:
        return None  # Will be handled separately
    if field.type_name == "id":
        return "str"
    if field.type_name == "string":
        if field.modifiers.format_type == "email":
            return "EmailStr"
        return "str"
    if field.type_name == "number" or field.type_name == "int":
        return "int"
    if field.type_name == "boolean":
        return "bool"
    return "str"


def _field_kwargs(field: InputField) -> str:
    """Generate Field(...) kwargs for constraints."""
    kwargs = []
    if field.modifiers.min_val is not None:
        kwargs.append(f"min_length={field.modifiers.min_val}")
    if field.modifiers.max_val is not None:
        kwargs.append(f"max_length={field.modifiers.max_val}")
    return ", ".join(kwargs)


def generate_schemas(spec: JourneySpec) -> str:
    """Generate the complete schemas.py file."""
    lines = [
        '"""',
        "AUTO-GENERATED by Journey compiler",
        "DO NOT EDIT — regenerate with: journey compile <source>.journey",
        '"""',
        "",
        "from datetime import datetime",
        "from typing import Optional",
        "",
        "from pydantic import BaseModel, EmailStr, Field",
        "",
    ]

    # Collect enum imports we'll need
    enum_imports = set()
    for step in spec.steps:
        for inp in step.inputs:
            if inp.enum_type:
                # Find the entity that has this enum defined
                for entity in spec.entities:
                    for f in entity.fields:
                        if f.enum_type and f.enum_type.values == inp.enum_type.values:
                            class_name = f"{entity.name}{f.name.title().replace('_', '')}"
                            enum_imports.add(class_name)

    if enum_imports:
        lines.append(f"from .models import {', '.join(sorted(enum_imports))}")
        lines.append("")

    # Generate request/response schemas for each step
    for step in spec.steps:
        lines.extend(_gen_request_schema(step, spec))
        lines.append("")
        lines.extend(_gen_response_schema(step, spec))
        lines.append("")

    # Error response schema
    lines.extend([
        "",
        "class ErrorResponse(BaseModel):",
        "    error: str",
        "    message: str",
        "    detail: Optional[str] = None",
        "",
    ])

    return "\n".join(lines)


def _gen_request_schema(step: Step, spec: JourneySpec) -> list[str]:
    class_name = f"{_step_class_name(step.name)}Request"
    lines = [f"class {class_name}(BaseModel):"]

    if not step.inputs:
        lines.append("    pass")
        return lines

    for inp in step.inputs:
        type_str = _pydantic_type(inp)
        kwargs = _field_kwargs(inp)

        if inp.enum_type:
            # Find matching enum from entities
            enum_cls = None
            for entity in spec.entities:
                for f in entity.fields:
                    if f.enum_type and f.enum_type.values == inp.enum_type.values:
                        enum_cls = f"{entity.name}{f.name.title().replace('_', '')}"
                        break
            if enum_cls:
                if inp.default:
                    lines.append(f"    {inp.name}: {enum_cls} = {enum_cls}.{inp.default}")
                elif not inp.required:
                    lines.append(f"    {inp.name}: {enum_cls} = {enum_cls}.{inp.enum_type.values[0]}")
                else:
                    lines.append(f"    {inp.name}: {enum_cls}")
            continue

        if kwargs:
            if not inp.required and inp.default:
                lines.append(f'    {inp.name}: {type_str} = Field({inp.default!r}, {kwargs})')
            else:
                lines.append(f"    {inp.name}: {type_str} = Field(..., {kwargs})")
        else:
            if not inp.required and inp.default:
                lines.append(f"    {inp.name}: {type_str} = {inp.default!r}")
            else:
                lines.append(f"    {inp.name}: {type_str}")

    return lines


def _gen_response_schema(step: Step, spec: JourneySpec) -> list[str]:
    class_name = f"{_step_class_name(step.name)}Response"
    lines = [f"class {class_name}(BaseModel):"]

    if not step.outputs:
        lines.append("    pass")
        return lines

    for out in step.outputs:
        # Infer the type from the expression
        expr = out.expression

        # If it's a plain string literal (not a dotted path)
        if "." not in expr and not expr.startswith("{"):
            lines.append(f'    {out.name}: str = {expr!r}')
            continue

        # Dotted paths — infer type from the entity field
        parts = expr.split(".")
        if len(parts) >= 2:
            # Try to infer type from entity definition
            entity_var = parts[0]  # e.g., "user", "workspace"
            field_name = parts[1]  # e.g., "id", "name"

            if field_name == "id":
                lines.append(f"    {out.name}: str")
            elif field_name == "name":
                lines.append(f"    {out.name}: str")
            elif field_name == "token":
                lines.append(f"    {out.name}: str")
            elif field_name == "expires_at":
                lines.append(f"    {out.name}: datetime")
            elif field_name == "role":
                # Find the enum
                for entity in spec.entities:
                    for f in entity.fields:
                        if f.name == "role" and f.enum_type:
                            enum_cls = f"{entity.name}{f.name.title().replace('_', '')}"
                            lines.append(f"    {out.name}: {enum_cls}")
                            break
                    else:
                        continue
                    break
                else:
                    lines.append(f"    {out.name}: str")
            else:
                lines.append(f"    {out.name}: str")
        else:
            lines.append(f"    {out.name}: str")

    return lines
