"""Generate SQLAlchemy models from JourneySpec entities."""

from ..parser.ast_nodes import Entity, Field, JourneySpec, StateType, EnumType


HEADER = '''"""
AUTO-GENERATED by Journey compiler
DO NOT EDIT — regenerate with: journey compile <source>.journey
"""

import enum
from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import Column, DateTime, Enum, ForeignKey, String
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    pass


def gen_id() -> str:
    return uuid4().hex


def now_utc() -> datetime:
    return datetime.now(timezone.utc)

'''


def _snake(name: str) -> str:
    """CamelCase -> snake_case."""
    result = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0:
            result.append("_")
        result.append(ch.lower())
    return "".join(result)


def _plural(name: str) -> str:
    """Naive pluralization for table names."""
    if name.endswith("s"):
        return name + "es"
    if name.endswith("y"):
        return name[:-1] + "ies"
    return name + "s"


def _gen_state_enum(entity_name: str, field: Field) -> str:
    """Generate a state enum class with transition validation."""
    st = field.state_type
    class_name = f"{entity_name}{field.name.title().replace('_', '')}".rstrip("s")
    if not class_name.endswith("Status"):
        class_name = f"{entity_name}Status"

    lines = [f"\nclass {class_name}(str, enum.Enum):"]
    for s in st.states:
        lines.append(f'    {s} = "{s}"')

    lines.append("")
    lines.append("    @classmethod")
    lines.append("    def _get_transitions(cls):")
    lines.append("        return {")
    for s in st.states:
        targets = st.transitions.get(s, [])
        lines.append(f'            "{s}": {targets},')
    lines.append("        }")
    lines.append("")
    lines.append(f'    def can_transition_to(self, target: "{class_name}") -> bool:')
    lines.append("        return target.value in self._get_transitions().get(self.value, [])")

    return "\n".join(lines), class_name


def _gen_enum_type(entity_name: str, field: Field) -> str:
    """Generate an enum class for enum fields."""
    et = field.enum_type
    class_name = f"{entity_name}{field.name.title().replace('_', '')}"

    lines = [f"\nclass {class_name}(str, enum.Enum):"]
    for v in et.values:
        lines.append(f'    {v} = "{v}"')

    return "\n".join(lines), class_name


def generate_models(spec: JourneySpec) -> str:
    """Generate the complete models.py file."""
    sections = [HEADER]
    enum_classes = {}  # field_key -> class_name mapping

    # First pass: generate all enum/state classes
    for entity in spec.entities:
        for field in entity.fields:
            key = f"{entity.name}.{field.name}"
            if field.state_type:
                code, class_name = _gen_state_enum(entity.name, field)
                sections.append(code)
                enum_classes[key] = class_name
            elif field.enum_type:
                code, class_name = _gen_enum_type(entity.name, field)
                sections.append(code)
                enum_classes[key] = class_name

    sections.append("")

    # Second pass: generate model classes
    for entity in spec.entities:
        sections.append(_gen_model_class(entity, enum_classes, spec))

    # Check if any step uses add_member — generate WorkspaceMember if so
    for step in spec.steps:
        for action in step.actions:
            if action.kind == "call" and action.target == "add_member":
                sections.append(_gen_workspace_member(enum_classes, spec))
                break

    return "\n".join(sections) + "\n"


def _gen_model_class(entity: Entity, enum_classes: dict, spec: JourneySpec) -> str:
    table_name = _plural(_snake(entity.name))
    lines = [f"\nclass {entity.name}(Base):"]
    lines.append(f'    __tablename__ = "{table_name}"')
    lines.append("")

    # Always add an id primary key
    lines.append("    id = Column(String, primary_key=True, default=gen_id)")

    has_state = False

    for field in entity.fields:
        key = f"{entity.name}.{field.name}"
        col_args = []

        if field.ref_entity:
            # Foreign key reference
            ref_table = _plural(_snake(field.ref_entity))
            fk = f'{ref_table}.id'
            lines.append(
                f'    {field.name}_id = Column(String, ForeignKey("{fk}"), nullable=False)'
            )
            # Also add relationship
            lines.append(
                f'    {field.name}_rel = relationship("{field.ref_entity}")'
            )
            continue

        if field.state_type:
            has_state = True
            enum_cls = enum_classes[key]
            default_state = field.state_type.states[0]
            lines.append(
                f"    {field.name} = Column(Enum({enum_cls}), nullable=False, default={enum_cls}.{default_state})"
            )
            # Add verification token for user entities with state
            if entity.name == "User":
                lines.append(
                    "    verification_token = Column(String, unique=True, default=gen_id)"
                )
            continue

        if field.enum_type:
            enum_cls = enum_classes[key]
            default_val = field.enum_type.values[0]
            lines.append(
                f"    {field.name} = Column(Enum({enum_cls}), nullable=False, default={enum_cls}.{default_val})"
            )
            continue

        if field.type_name == "timestamp":
            if field.modifiers.auto:
                lines.append(f"    {field.name} = Column(DateTime, default=now_utc)")
            else:
                lines.append(f"    {field.name} = Column(DateTime)")
            continue

        # String field
        col_kwargs = []
        if field.modifiers.hashed:
            lines.append(
                f"    {field.name}_hash = Column(String, nullable=False)"
            )
            continue
        if field.modifiers.unique:
            col_kwargs.append("unique=True")
            col_kwargs.append("index=True")
        if field.modifiers.auto and field.name == "token":
            if "unique=True" not in col_kwargs:
                col_kwargs.append("unique=True")
            col_kwargs.append("default=gen_id")

        col_kwargs_str = ", ".join(["String"] + col_kwargs + ["nullable=False"])

        lines.append(f"    {field.name} = Column({col_kwargs_str})")

    # Add transition method if entity has state
    if has_state:
        for field in entity.fields:
            if field.state_type:
                enum_cls = enum_classes[f"{entity.name}.{field.name}"]
                lines.append("")
                lines.append(f"    def transition_to(self, new_status: {enum_cls}) -> None:")
                lines.append(f"        current = {enum_cls}(self.{field.name}) if isinstance(self.{field.name}, str) else self.{field.name}")
                lines.append(f"        if not current.can_transition_to(new_status):")
                lines.append(f'            raise ValueError(f"Invalid transition: {{current.value}} -> {{new_status.value}}")')
                lines.append(f"        self.{field.name} = new_status")

    return "\n".join(lines)


def _gen_workspace_member(enum_classes: dict, spec: JourneySpec) -> str:
    """Generate WorkspaceMember join table model."""
    # Find the role enum class
    role_enum = None
    for key, cls_name in enum_classes.items():
        if "role" in key.lower():
            role_enum = cls_name
            break

    lines = [
        "",
        "",
        "class WorkspaceMember(Base):",
        '    __tablename__ = "workspace_members"',
        "",
        "    id = Column(String, primary_key=True, default=gen_id)",
        '    workspace_id = Column(String, ForeignKey("workspaces.id"), nullable=False)',
        '    user_id = Column(String, ForeignKey("users.id"), nullable=False)',
    ]

    if role_enum:
        lines.append(f"    role = Column(Enum({role_enum}), nullable=False)")
    else:
        lines.append("    role = Column(String, nullable=False)")

    lines.append("    joined_at = Column(DateTime, default=now_utc)")

    return "\n".join(lines)
